version: '2'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    links:
      - php
    restart: always
    environment:
      - DOMAINS=lemon.takuru.net -> http://php
      - STAGE

  php:
    build: docker/php
    volumes:
      - .:/usr/src/myapp
    working_dir: /usr/src/myapp/laravel 
    entrypoint: "php artisan serve --port=80 --host=0.0.0.0" 

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - TZ="Asia/Tokyo"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
       - 127.0.0.1:8080:80
    links:
      - db


#  Analyze用:一旦つかわない
#  php:
#    build: docker/php
#    volumes:
#      - ./../:/usr/src/myapp
#    working_dir: /usr/src/myapp
#    entrypoint: port_analyze/run.sh
#    links:
#      - db
#
#  grafana:
#    image: grafana/grafana
#    ports:
#      - 127.0.0.1:3000:3000
#    links:
#      - db
